### PR TITLE
Add federated execution debugging argument example.

### PR DESCRIPTION
**Pull request by Jakio815**

### CODE REVIEW

**Comment by Jakio815** [comment]
@lhstrh Don't see a request review button on this repo.

**Review by petervdonovan — APPROVED** [review]
Looks good. Thanks Dongha!

**Comment by Jakio815** [comment]
@petervdonovan Oh, I think I added it in the wrong document. I should've done it on the newest version, but it seems to be on 0.7.0. I think I got to there because I pushed the `edit page` button on the 0.7.0 version, not the nightly one...

**Comment by lhstrh** [comment]
@Jakio815 you just open a new PR that fixes this.

**Pull request merged**
