### PR TITLE
Update the Target Description web page

### PR DESCRIPTION
**Pull request by chanijjani**
- Update the Rust target document parts regarding to #276

### CODE REVIEW

**Comment by chanijjani** [comment]
Could someone pull this PR to check builds and deploy this change?

**Comment by chanijjani** [comment]
No automatic CI check?

**Review by lhstrh — COMMENTED** [review]
What do the curly brackets do?

**Comment by chanijjani** [comment]
> What do the curly brackets do?

I intended to leave the parts as backups but just dropped them for clarification.

**Review by lhstrh — APPROVED** [review]
Looks great, thanks for these changes, @chanijjani!

**Review by lhstrh — CHANGES_REQUESTED** [review]
Actually, there is one thing missing here. These changes should also be reflected in the versioned docs. Could you add those to this PR as well?

**Comment by chanijjani** [comment]
**Rust** target description validation 
- Example and method used
   : Run the binary of [CounterProgram.lf](https://github.com/lf-lang/playground-lingua-franca/blob/main/examples/Rust/src/CounterProgram.lf) after applying the target property and compiling with ```lfc``` (version: 0.9.0)

| Target Property | Supported (Web) | Supported (Actual) | Compilation & Execution | Review Comment | 
| -- | -- | -- | -- | -- |
| auth, build, compiler, docker, files, no-runtime-validation, protobufs, runtime-version, scheduler | X | X | N/A | None |
| buildtype | O | O | O | None <br> (Binary size: `Debug`=40,671,312bytes <br> `Release`=4,450,760bytes <br> `RelWithDebInfo`=27,350,408bytes <br> `MinSizeRel`=4,179,936bytes) |
| cargo-dependencies, fast, no-compile, single-file-project, single-threaded, timeout, workers, Command-Line Arguments | O | O | O | None |
| cargo-features | O | O | O | It would be good to add usage examples later. |
| **external-runtime-path** | O | O | X | **Not able to know how to use** |
| export-dependency-graph | O | O | O | 1) This option works only when `cargo-features` is set to `cli` and the command line option `--export-graph` is given. |
| logging | X | O | O | Check later |
| **rust-include** | O | O | O | **The link `Linking support files` doesn't work.** |

**Comment by chanijjani** [comment]
@lhstrh Would the above table be enough for the versioned documents? Or could you let me share a guide for the documents?

**Comment by lhstrh** [comment]
I'm not sure what you mean, @chanijjani, but what I'm asking for is to simply replicate the changes you made in this PR across the files in the `versioned_docs` directory. At a minimum, v0.9.0 should reflect these changes. If we don't do this, the changes will only appear in the "nightly" docs, and I expect most people will be looking at the versioned docs.

**Comment by chanijjani** [comment]
@lhstrh Oh, I understand. Let me do that immediately.

**Comment by chanijjani** [comment]
@lhstrh Could you review this PR again?

**Review by lhstrh — APPROVED** [review]
Looks good! Thanks again!

**Pull request merged**
