### PR TITLE
Update doc for lf-lang/lingua-franca#1580

### PR DESCRIPTION
**Pull request by oowekyala**
Update the code examples and format them. All the standalone LF files have been formatted automatically by LFF so there should be no surprise there.

### CODE REVIEW

**Comment by edwardalee** [comment]
When should this PR be merged?  If we merge it now, then none of the code examples will work properly with the current release. This suggests that it should only be merged after the next release.  But since this touches every source file, this will be very painful.  There will be many conflicts.

**Comment by lhstrh** [comment]
We should merge it after the new release, which should happen soon. There are currently no conflicts with this PR.

**Comment by lhstrh** [comment]
@edwardalee, I'm assuming that #145 has subsumed this PR, meaning this should probably be closed?

**Comment by edwardalee** [comment]
Yes, this should be closed.

Please do not run the formatter on the website examples because it will inline one-line reactions and make the docs much harder to read.

**Pull request closed without merging**
